### ISSUE TITLE
add llamas

### ISSUE THREAD

**Issue by kittokin** [Ineusia/ChestedHorseRemover#1]
I think it's also a good idea to add an event that also detects llamas because they can also be used for duping as [shown in this video](https://www.youtube.com/watch?v=6zJ6MRz3Glg).

**Comment by Ineusia** [comment]
ChestedHorse covers all chest bearing animals, including Llamas
https://papermc.io/javadocs/paper/1.13/org/bukkit/entity/ChestedHorse.html
